spring:
  profiles:
    active: local-keycloak
server:
  http2:
    enabled: true
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: gateway,health,info
rflux:
  rocket-service:
    id: rocket-service
  auth-service:
    id: auth-service
---
spring:
  profiles: local-keycloak
spring.profiles.include: local,keycloak
keycloak:
  url: http://localhost:8000
---
spring:
  profiles: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/auth/realms/rflux
rflux:
  auth-service:
    url: ${keycloak.url}
---
spring:
  profiles: local
rflux:
  rocket-service:
    url: http://localhost:8081
