spring:
  profiles:
    active: local-keycloak
server:
  http2:
    enabled: true
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: gateway,health,info
rflux:
  rocket-service:
    path: rocket-service
    id: rockets
---
spring:
  profiles: local-keycloak
spring.profiles.include: local,keycloak
keycloak:
  url: http://localhost:8000
---
spring:
  profiles: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/auth/realms/${keycloak.realm}
keycloak:
  realm: rflux
rflux:
  auth-service:
    uri: ${keycloak.url}
    id: auth
    path: auth-service
---
spring:
  profiles: local
rflux:
  rocket-service:
    uri: http://localhost:8081
